//go:build ignore

package main

import (
	"archive/zip"
	"crypto/sha512"
	"encoding/xml"
	"fmt"
	"io"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func main() {
	// 可通过 CLDR_VERSION 指定版本, 不指定则默认使用 latest
	// https://unicode.org/Public/cldr/latest 会自动跳转到当前版本号
	fmt.Printf("version: %s\n", version)
	// 下载当前指定版本的数据(SHASUM512.txt + core.zip)
	downloadCldrCoreZip()
	// 校验数据并解压
	validateAndUnzip()
	// 生成代码
	genCode()
}

// version 使用的 CLDR 数据的版本
var version = cldrVersion()

func cldrVersion() string {
	var v = strings.TrimSpace(os.Getenv("CLDR_VERSION"))
	if v != "" && v != "latest" {
		return v
	}
	url := "https://unicode.org/Public/cldr/latest"
	req, err := http.NewRequest("HEAD", url, nil)
	if err != nil {
		panic(err)
	}
	resp, err := noRedirectClient.Do(req)
	if err != nil {
		panic(err)
	}
	loc := resp.Header.Get("Location")
	if loc == "" {
		panic("unexpected empty location")
	}
	// http://unicode.org/Public/cldr/latest -> http://unicode.org/Public/cldr/48
	v = loc[strings.LastIndex(loc, "/")+1:]
	return v
}

var noRedirectClient = &http.Client{
	CheckRedirect: func(req *http.Request, via []*http.Request) error {
		return http.ErrUseLastResponse
	},
}

func downloadCldrCoreZip() {
	downloadCldrFile("hashes/SHASUM512.txt")
	downloadCldrFile("core.zip")
}

func downloadCldrFile(path string) {
	path = fmt.Sprintf("cldr/%v/%s", version, path)
	dir := filepath.Dir(path)
	err := os.MkdirAll(dir, 0755)
	if err != nil {
		panic(fmt.Errorf("mkdir %v failed: %w", dir, err))
	}

	// 判断已存在，不重复下载
	if _, err = os.Stat(path); err == nil {
		fmt.Printf("%v already exists\n", path)
		return
	}

	url := fmt.Sprintf("https://unicode.org/Public/%s", path)
	resp, err := http.Get(url)
	if err != nil {
		panic(fmt.Errorf("download %v failed: %w", url, err))
	}
	defer resp.Body.Close()

	file, err := os.Create(path)
	if err != nil {
		panic(fmt.Errorf("create %v failed: %w", path, err))
	}
	defer file.Close()

	_, err = io.Copy(file, resp.Body)
	if err != nil {
		panic(fmt.Errorf("save %v failed: %w", path, err))
	}
	fmt.Printf("%v downloaded\n", path)
}

func validateAndUnzip() {
	file, err := os.Open(fmt.Sprintf("cldr/%v/hashes/SHASUM512.txt", version))
	if err != nil {
		panic(fmt.Errorf("open %v failed: %w", file, err))
	}
	defer file.Close()
	b, err := io.ReadAll(file)
	if err != nil {
		panic(fmt.Errorf("read %v failed: %w", file, err))
	}

	// 6727fb2c130b0b1c13067b8f1c5292b6ebe87f03c1a4449fc84490f405e249fabf3a283f2a8e428086e7e840975c94bce2aaa300cbaa42c64dac3219696c14f0  cldr-common-48.1.zip
	// 3b9e28dd192da7e2089044a264cecd80093beb0983a0475624c1717adb6ea8382e607e5d23b32ea6a8a4124ad673eca203e2eda5235d06c8f967cdd2137e8823  cldr-keyboards-48.1.zip
	// 6727fb2c130b0b1c13067b8f1c5292b6ebe87f03c1a4449fc84490f405e249fabf3a283f2a8e428086e7e840975c94bce2aaa300cbaa42c64dac3219696c14f0  core.zip
	// 3b9e28dd192da7e2089044a264cecd80093beb0983a0475624c1717adb6ea8382e607e5d23b32ea6a8a4124ad673eca203e2eda5235d06c8f967cdd2137e8823  keyboards.zip
	// fa0af3dbe96e3c7ec6f7da4be52cd4bd4338e192eb755cdb2ac71d030a4020cc57c1ed09fcaea19cb38befc4f371bc4bad9f8b164e5f9039d2acc6e2f4f96494  cldr-code.jar
	// fa0af3dbe96e3c7ec6f7da4be52cd4bd4338e192eb755cdb2ac71d030a4020cc57c1ed09fcaea19cb38befc4f371bc4bad9f8b164e5f9039d2acc6e2f4f96494  cldr-tools-48.1.jar

	// 校验 core.zip 的校验和是否与 SHASUM512.txt 中的校验和一致
	// 如果不一致，报错
	// 如果一致，继续生成代码
	coreZipPath := fmt.Sprintf("cldr/%v/core.zip", version)
	file, err = os.Open(coreZipPath)
	if err != nil {
		panic(fmt.Errorf("open %v failed: %w", coreZipPath, err))
	}
	defer file.Close()
	hash := sha512.New()
	if _, err := io.Copy(hash, file); err != nil {
		panic(fmt.Errorf("calc %v sha512 failed: %w", coreZipPath, err))
	}
	hashSum := hash.Sum(nil)
	hashSumStr := fmt.Sprintf("%x", hashSum)

	// 校验 core.zip 的校验和是否与 SHASUM512.txt 中的校验和一致
	// 如果不一致，报错
	// 如果一致，继续生成代码
	if !strings.Contains(string(b), hashSumStr+"  core.zip") {
		panic(fmt.Errorf("core.zip sha512 sum not match: %v", hashSumStr))
	}
	fmt.Printf("%v sha512 sum match: %v\n", coreZipPath, hashSumStr)
}

func genCode() {
	coreZipPath := fmt.Sprintf("cldr/%v/core.zip", version)
	fmt.Printf("gen code via %s\n", coreZipPath)

	// 打开 zip 文件
	zipfile, err := zip.OpenReader(coreZipPath)
	if err != nil {
		panic(fmt.Errorf("open %v failed: %w", coreZipPath, err))
	}
	defer zipfile.Close()
	// 将压缩包内的文件按字母顺序排序
	sort.Slice(zipfile.File, func(i, j int) bool {
		return zipfile.File[i].Name < zipfile.File[j].Name
	})

	// Create: 新建或清空文件
	f, err := os.Create("table.gen.go")
	if err != nil {
		panic(fmt.Errorf("create table.gen.go failed: %w", err))
	}
	defer f.Close()

	// 开始生成文件
	f.WriteString(`// Code generated by "go run gen.go". DO NOT EDIT.

package language

`)
	fmt.Fprintf(f, "var cldrVersion = %q\n\n", version)
	f.WriteString("var (\n")

	var allCode []string
	// 遍历每种语言数据
	for _, file := range zipfile.File {
		if strings.HasPrefix(file.Name, "common/main/") && strings.HasSuffix(file.Name, ".xml") {
			r, err := file.Open()
			if err != nil {
				panic(fmt.Errorf("open %v failed: %w", file.Name, err))
			}
			defer r.Close()
			// 解析 xml 格式
			ldml := parseXml(r)
			// 生成相应语言的变量
			code, err := writeVar(f, ldml)
			if err != nil {
				panic(fmt.Errorf("write var %v failed: %w", code, err))
			}
			allCode = append(allCode, code)
		}
	}

	f.WriteString(")") // var ()
	f.WriteString("\n\n")

	f.WriteString("var cldrItems = []*cldrItem{")
	for i, code := range allCode {
		if i > 0 {
			f.WriteString(", ")
		}
		f.WriteString("_")
		f.WriteString(code)
	}
	f.WriteString("}") // var cldrItems
	f.WriteString(`

var cldrItemMap = make(map[string]*cldrItem, len(cldrItems))

func init() {
	for _, item := range cldrItems {
		tag := item.tag
		code := tag.String()
		cldrItemMap[code] = item
	}

	for _, item := range cldrItems {
		parent := item.Parent()
		item.parent = parent
		parent.children = append(parent.children, item)
	}
}

`)
}

func parseXml(file io.Reader) *Ldml {
	b, err := io.ReadAll(file)
	if err != nil {
		return nil
	}
	var ldml Ldml
	err = xml.Unmarshal(b, &ldml)
	if err != nil {
		return nil
	}
	return &ldml
}

func writeVar(f *os.File, ldml *Ldml) (string, error) {
	var sb strings.Builder
	id := ldml.Identity
	parts := []string{}
	parts = append(parts, id.Language.Type) // 语言
	if s := id.Script.Type; s != "" {       // 书写格式
		parts = append(parts, s)
	}
	if s := id.Territory.Type; s != "" { // 地区
		parts = append(parts, s)
	}
	if s := id.Variant.Type; s != "" { // 变体
		parts = append(parts, s)
	}
	code := strings.Join(parts, "_")

	sb.WriteString("\t_")
	sb.WriteString(code)
	sb.WriteString(" = &cldrItem{\n")
	// Tag 字段
	sb.WriteString("\t\ttag: Tag{\n")
	fmt.Fprintf(&sb, "\t\t\tLanguage: %q,\n", id.Language.Type)
	if s := id.Script.Type; s != "" {
		fmt.Fprintf(&sb, "\t\t\tScript: %q,\n", s)
	}
	if s := id.Territory.Type; s != "" {
		fmt.Fprintf(&sb, "\t\t\tRegion: %q,\n", s)
	}
	if v := id.Variant.Type; v != "" {
		fmt.Fprintf(&sb, "\t\t\tVariant: []string{%q},\n", v)
	}
	sb.WriteString("\t\t},\n") // tag: Tag{}

	// 格式字段/语言格式/字段并列格式/键值对格式
	pattern := ldml.LocaleDisplayNames.LocaleDisplayPattern
	if s := pattern.LocalePattern; s != "" {
		fmt.Fprintf(&sb, "\t\tlocalePattern:        %q,\n", s)
	}
	if s := pattern.LocaleSeparator; s != "" {
		fmt.Fprintf(&sb, "\t\tlocaleSeparator:      %q,\n", s)
	}
	if s := pattern.LocaleKeyTypePattern; s != "" {
		fmt.Fprintf(&sb, "\t\tlocaleKeyTypePattern: %q,\n", s)
	}

	// 各语言的本地化名称
	if list := ldml.LocaleDisplayNames.Languages.Language; len(list) > 0 {
		writeMapField(&sb, "languages", list)
	}
	if list := ldml.LocaleDisplayNames.Scripts.Script; len(list) > 0 {
		writeMapField(&sb, "scripts", list)
	}
	if list := ldml.LocaleDisplayNames.Territories.Territory; len(list) > 0 {
		writeMapField(&sb, "regions", list)
	}
	if list := ldml.LocaleDisplayNames.Variants.Variant; len(list) > 0 {
		writeMapField(&sb, "variants", list)
	}

	sb.WriteString("\t}\n") // code = &locale{}

	_, err := f.WriteString(sb.String())
	return code, err
}

func writeMapField(sb *strings.Builder, field string, list []TypeAttrValue) {
	fmt.Fprintf(sb, "\t\t%s: map[string]string{\n", field)
	for _, item := range list {
		key := item.Type
		if item.Alt != "" {
			key += "-" + item.Alt
		}
		if item.Menu != "" {
			key += "-" + item.Menu
		}
		fmt.Fprintf(sb, "\t\t\t%q: %q,\n", key, item.Value)
	}
	fmt.Fprintf(sb, "\t\t},\n")
}

type Ldml struct {
	XMLName            struct{}           `xml:"ldml"`
	Identity           Identity           `xml:"identity"`
	LocaleDisplayNames LocaleDisplayNames `xml:"localeDisplayNames"`
}

type Identity struct {
	Language  TypeAttrValue `xml:"language"`
	Script    TypeAttrValue `xml:"script"`
	Territory TypeAttrValue `xml:"territory"`
	Variant   TypeAttrValue `xml:"variant"`
}

type TypeAttrValue struct {
	Type  string `xml:"type,attr"`
	Alt   string `xml:"alt,attr,omitempty"`
	Menu  string `xml:"menu,attr,omitempty"`
	Draft string `xml:"draft,attr,omitempty"`
	Value string `xml:",chardata"`
}

type LocaleDisplayNames struct {
	LocaleDisplayPattern LocaleDisplayPattern `xml:"localeDisplayPattern"`
	Languages            Languages            `xml:"languages"`
	Scripts              Scripts              `xml:"scripts"`
	Territories          Territories          `xml:"territories"`
	Variants             Variants             `xml:"variants"`
}

type LocaleDisplayPattern struct {
	// {0}（{1}）: {0}=languages 语言 {1}=territories 地区
	LocalePattern string `xml:"localePattern"`
	// {0}，{1}: 多个项目并列时的格式（使用全角逗号）
	LocaleSeparator string `xml:"localeSeparator"`
	// {0}：{1}: 键值对表示时的格式（使用全角冒号）
	LocaleKeyTypePattern string `xml:"localeKeyTypePattern"`
}

type Languages struct {
	Language []TypeAttrValue `xml:"language"`
}

type Scripts struct {
	Script []TypeAttrValue `xml:"script"`
}

type Territories struct {
	Territory []TypeAttrValue `xml:"territory"`
}

type Variants struct {
	Variant []TypeAttrValue `xml:"variant"`
}
